[package]
name = "symbolic-cabi"
version = "2.0.4"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
C interface wrapper for symbolic, a library to symbolicate and process stack
traces from native applications, minidumps, minified JavaScripts or ProGuard
optimized Android apps.
"""

[lib]
name = "symbolic"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
uuid = "0"
symbolic-common = { version = "2.0.4", path = "../common", features = ["with_dwarf", "with_objects", "with_sourcemaps"] }
symbolic-demangle = { version = "2.0.4", path = "../demangle" }
symbolic-debuginfo = { version = "2.0.4", path = "../debuginfo" }
symbolic-symcache = { version = "2.0.4", path = "../symcache" }
symbolic-sourcemap = { version = "2.0.4", path = "../sourcemap" }
symbolic-proguard = { version = "2.0.4", path = "../proguard" }
symbolic-minidump = { version = "2.0.4", path = "../minidump" }
